kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kyma-installer
  name: {{ .Release.Name }}-kyma-installer-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "patch"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: istio-system
  name: {{ .Release.Name }}-istio-system-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "patch"]
