jobs:
  crdsInConfigMap: 20
  image:
    repository: eu.gcr.io/kyma-project/test-infra/alpine-kubectl
    tag: "v20200617-32c1f3ff"
  installer:
    namespace: kyma-installer

global:
  isLocalEnv: false
  disableLegacyConnectivity: false
  # Provide list of CRD file names (without path!) that will be excluded from installation.
  # The files are in the ./files directory of this chart.
  # Using this mechanism you can exclude a CRD in specific environment where it's functionality isn't used.
  skipCrds:

containerRegistry:
  path: eu.gcr.io/kyma-project

image:
  repository: eu.gcr.io/kyma-project/incubator/develop/api-gateway-controller
  tag: "978664da"
  # Image pull policy
  pullPolicy: IfNotPresent
