jobs:
  crdsInConfigMap: 20
  image:
    repository: eu.gcr.io/kyma-project/test-infra/alpine-kubectl
    tag: "v20200617-32c1f3ff"
  installer:
    namespace: kyma-installer

global:
  isLocalEnv: false
  disableLegacyConnectivity: false
  skipCrds:
    - "cert-manager.io.crd.1.yaml"
    - "cert-manager.io.crd.2.yaml"

containerRegistry:
  path: eu.gcr.io/kyma-project

image:
  repository: eu.gcr.io/kyma-project/incubator/develop/api-gateway-controller
  tag: "978664da"
  # Image pull policy
  pullPolicy: IfNotPresent
