service:
  port: 8000
  name: iam-kubeconfig-service

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 32Mi
global:
  isLocalEnv: false
  istio:
    gateway:
      name: kyma-gateway
  containerRegistry:
    path: eu.gcr.io/kyma-project
  iam_kubeconfig_service:
    dir:
    version: 1af8f7a8

init:
  targetSecret:
    name: kyma-ca-key-pair
    namespace: istio-system
  image:
    name: eu.gcr.io/kyma-project/test-infra/alpine-kubectl
    tag: "v20200617-32c1f3ff"