---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        tlsSecret: ingress-tls-cert
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      {{ if .Values.global.isLocalEnv }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{ end }}
      containers:
      - image: eu.gcr.io/kyma-project/pr/configurations-generator:PR-2743
        name: {{ template "name" . }}
        command: [
          "/app",
          "-kube-config-cluster-name={{ .Values.global.domainName }}",
          "-kube-config-url=https://apiserver.{{ .Values.global.domainName }}",
          "-kube-config-ca-file=/etc/ingress-tls-cert/tls.crt",
          "-oidc-issuer-url=https://dex.{{ .Values.global.domainName }}",
          "-oidc-client-id=kyma-client"
        ]
        ports:
          - name: http
            containerPort: 8000
        volumeMounts:
        - name: ingress-tls-cert
          mountPath: "/etc/ingress-tls-cert"
          readOnly: true
      volumes:
      - name: ingress-tls-cert
        secret:
          secretName: ingress-tls-cert
