apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: kyma-cert-manager-config
data:
  config.yaml: |-
{{.Files.Get "files/cert-manager-config.yaml" | printf "%s" | indent 4}}

