apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  annotations:
spec:
  template:
    metadata:
      name: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-service-account
      restartPolicy: Never
      containers:
      - name: {{ .Release.Name }}
        image: tsmsap/xip-patch:15-29
        env:
        - name: EXTERNAL_PUBLIC_IP
          value: {{ .Values.global.loadBalancerIP }}
        - name: INGRESSGATEWAY_SERVICE_NAME
          value: istio-ingressgateway
        - name: GLOBAL_DOMAIN
          value: {{ .Values.global.domainName }}
        - name: GLOBAL_TLS_CERT
          value: {{ .Values.global.tlsCrt }}
        - name: GLOBAL_TLS_KEY
          value: {{ .Values.global.tlsKey }}
        - name: INGRESS_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: net-global-overrides
              key: global.ingress.domainName
              optional: true
        - name: INGRESS_TLS_CERT
          valueFrom:
            configMapKeyRef:
              name: net-global-overrides
              key: global.ingress.tlsCrt
              optional: true
        - name: INGRESS_TLS_KEY
          valueFrom:
            configMapKeyRef:
              name: net-global-overrides
              key: global.ingress.tlsKey
              optional: true
        volumeMounts:
          - mountPath: /etc/cert-config
            name: cert-config
            readOnly: true
      volumes:
        - name: cert-config
          configMap:
            name: kyma-cert-manager-config
