{{ if not .Values.global.isLocalEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: kyma-istio-control-plane-config
data:
  config.yaml: |-
{{.Files.Get "files/kyma_cluster_istio_control_plane.yaml" | printf "%s" | indent 4}}
{{ if .Values.kyma_istio_control_plane }}
  #This additional user-provided definition is merged with the default one
  overrides.yaml: |-
{{ .Values.kyma_istio_control_plane | printf "%s" | indent 4 }}
{{ end }}
{{ end }}
