apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: kyma-istio-config-minikube
data:
  config.yaml: |-
{{.Files.Get "files/kyma_minikube_istio_control_plane.yaml" | printf "%s" | indent 4}}
{{ if .Values.kyma_istio_control_plane }}
  overrides.yaml: |-
{{ .Values.kyma_istio_control_plane | printf "%s" | indent 4 }}
{{ end }}

