apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "api-gateway-migrator.name" . }}-job
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ template "api-gateway-migrator.name" . }}-job
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ template "api-gateway-migrator.name" . }}-account
      restartPolicy: Never
      containers:
        - name: migrator
          image: colunira/api-migrator:cmd
          command:
            - bash
            - -c
            - |
              /app/api-gateway-migrator --omit-apis-with-labels=migration/status
              echo "insert kubectl delete here"