apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "api-gateway-migrator.name" . }}-job
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ template "api-gateway-migrator.name" . }}-job
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ template "api-gateway-migrator.name" . }}-account
      restartPolicy: Never
      containers:
        - name: migrator
          image: eu.gcr.io/kyma-project/api-gateway-migrator:PR-7867
          command:
            - bash
            - -c
            - |
              set -e
              echo "Starting migration"
              date
              /app/api-gateway-migrator --label-blacklist=migration/status
              echo "Removing migrated apis"
              kubectl delete apis -l migration/status=migrated --all-namespaces
              echo "Migration finished"
              date
