---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "api-gateway-migrator.name" . }}-account
  namespace:  {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "api-gateway-migrator.name" . }}-role
  namespace:  {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
    #API Gateway resources
  - apiGroups: ["gateway.kyma-project.io"]
    resources: ["apis", "apis/status", "apirules", "apirules/status"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "api-gateway-migrator.name" . }}-role-binding
  namespace:  {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "api-gateway-migrator.name" . }}-account # Service account assigned to the api-gateway-migrator pod.
    namespace:  {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "api-gateway-migrator.name" . }}-role
