{{- $apiserverUrl := .Values.global.isLocalEnv | ternary "https://apiserver.$DOMAIN:9443" "https://apiserver.$DOMAIN" -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        tlsSecret: ingress-tls-cert
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    spec:
      {{ if .Values.global.isLocalEnv }}
      hostAliases:
      - ip: {{ .Values.global.minikubeIP }}
        hostnames:
          - "dex.{{ .Values.global.ingress.domainName }}"
      {{ end }}
      initContainers:
        - image: {{ .Values.init.image.name }}:{{ .Values.init.image.tag}}
          name: cert-injector
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: cert-injector-sa-token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            - name: shared-data
              mountPath: /injected-certs/
          command:
            - /bin/sh
            - -c
            - |
              kubectl get secret -n {{ .Values.init.targetSecret.namespace }} {{ .Values.init.targetSecret.name }} -o jsonpath='{.data.tls\.crt}' > /injected-certs/tls.crt
      containers:
      - image: {{ .Values.global.containerRegistry.path }}/{{ .Values.global.iam_kubeconfig_service.dir }}iam-kubeconfig-service:{{ .Values.global.iam_kubeconfig_service.version }}
        name: {{ template "name" . }}
        command:
          - sh
          - -c
        {{ if .Values.global.environment.gardener }}
          - /app/app -kube-config-cluster-name=$DOMAIN -kube-config-url={{ $apiserverUrl }} -kube-config-ca-file=/etc/apiserver-proxy-tls-cert/tls.crt -oidc-issuer-url=https://dex.{{ .Values.global.ingress.domainName }} -oidc-client-id=kyma-client
        {{ else }}
          - /app/app -kube-config-cluster-name=$DOMAIN -kube-config-url={{ $apiserverUrl }} -kube-config-ca-file=/etc/apiserver-proxy-tls-cert/tls.crt -oidc-issuer-url=https://dex.{{ .Values.global.ingress.domainName }} -oidc-client-id=kyma-client -oidc-ca-file=/etc/dex-tls-cert/tls.crt
        {{ end  }}
        envFrom:
        - configMapRef:
            name: apiserver-proxy
        ports:
          - name: http
            containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9000
          initialDelaySeconds: 45
          periodSeconds: 10
          failureThreshold: 10
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: apiserver-proxy-tls-cert
          mountPath: "/etc/apiserver-proxy-tls-cert"
        - name: shared-data
          mountPath: /etc/dex-tls-cert/
      volumes:
      - name: apiserver-proxy-tls-cert
        secret:
          secretName: apiserver-proxy-tls-cert
      - name: shared-data
        emptyDir: {}
      - name: cert-injector-sa-token
        secret:
          secretName: apiserver-proxy-cert-injector-sa-token
