hydraServer:
  port: 4444
  adminPort: 4445
  image:
    repository: oryd/hydra
    tag: v1.0.0-rc.8
  config:
    oauth2:
      shareErrorDebug: "1"
    databaseUrl: memory
    oidc:
      subjectTypesSupported: "public,pairwise"
  service:
    port: 80
    adminPort: 4445
loginConsent:
  name: oauth2-login-consent
  port: 3000
  image:
    repository: tsmsap/hydra-dex
    tag: test3_1
  dexJwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys
