apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "name" . }}-cert-injector
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}-cert-injector-sa-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ template "name" . }}-cert-injector
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "name" . }}-cert-injector
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames:
    - {{ .Values.init.targetSecret.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "name" . }}-cert-injector
  namespace: {{ .Values.init.targetSecret.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "name" . }}-cert-injector
subjects:
  - kind: ServiceAccount
    name: {{ template "name" . }}-cert-injector
    namespace: {{ .Release.Namespace }}
