apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: kyma-ca-issuer
  namespace: istio-system
spec:
  ca:
    secretName: kyma-ca-key-pair
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kyma-gateway-crt
  namespace: istio-system
spec:
  duration: 720h
  renewBefore: 10m
  keySize: 4096
  organization: # For debugging purposes
  - kyma2
  commonName: "*{{.Values.global.ingress.domainName}}"
  dnsNames:
  - "*.{{.Values.global.ingress.domainName}}"
  secretName: kyma-gateway-certs
  issuerRef:
    name: kyma-ca-issuer
    kind: Issuer
