apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kyma-gateway-certs
spec:
  duration: 720h # 30d
  renewBefore: 360h # 15d
  keySize: 4096
  organization: # For debugging purposes
  - Kyma
  commonName: {{ .Values.global.domainName }}
  dnsNames:
  - "*.{{ .Values.global.domainName }}"
  secretName: kyma-gateway-certs
  issuerRef:
    name: kyma-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
