apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: kyma-ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: kyma-ca-key-pair
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kyma-gateway-certs
  namespace: {{ .Release.Namespace }}
spec:
  duration: 720h
  renewBefore: 10m
  keySize: 4096
  organization: # For debugging purposes
  - kyma2
  commonName: {{ .Values.global.domainName }}
  dnsNames:
  - "*.{{ .Values.global.domainName }}"
  secretName: kyma-gateway-certs
  issuerRef:
    name: kyma-ca-issuer
    kind: Issuer
    group: cert-manager.io
